development:
  adapter: postgresql
  encoding: unicode
  database: riderank
  host: localhost
  pool: 5
  username: postgres
  password: qazwsx12
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: riderank-test
  host: localhost
  pool: 5
  username: postgres
  password: qazwsx12
  port: 5432
